### ISSUE TITLE
Unable to set custom font

### ISSUE THREAD

**Issue by zakora** [portacle/config#1]
According to the portacle help file, custom configuration should be kept under `config/user.el`.
I added the following to this file in order to change to default font:
```elisp
(set-face-attribute 'default nil :height 130 :family "Iosevka Term")
```
But the font is not changed after restarting portacle.
If I do a `C-M-x` on this line, then the font is changed.

Could you provide an instruction on how to change to default font of portacle?

**Comment by Shinmera** [comment]
The default font is set in Portacle's configuration [here](https://github.com/portacle/emacsd/blob/master/portacle-window.el#L18), which I believe overrides your defeault face attribute. In order to override the way Portacle does it, putting something like `(add-to-list 'initial-frame-alist  '(font . "Iosevka Term"))` into your `user.el` should do the trick instead.

**Comment by zakora** [comment]
Indeed, it did the trick!
Thanks for you work and for answering quickly.
